### ISSUE TITLE
Consolidate/reconcile itisatracker.com and trackertest.org

### ISSUE THREAD

**Issue by groovecoder** [mozilla/trackertest#10]
Our block-list includes itisatracker.com, but this repo links to trackertest.org.

Which site should we use? And/or - what is the purpose of each site, if they are different? We should add a README here to explain it.

**Comment by fmarier** [comment]
I added a mention of the alias domains in c0d1acdbca2d55c769731fc239851967c711a96f.

As far as documenting which lists these test domains are part of, this is already done here: https://wiki.mozilla.org/Security/Tracking_protection#QA
